# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a79f6327df7ad58e9fa09afb67ecb468a586de11833a362b22a8f8a928fb47a9c91504997f938ef9cdd8bc34aa069b26ccb8ed0b15a3054a3f54a6b8ef46d2c4

test:
  secret_key_base: affdbedd795f5f2564ad9a054d34ee875a8f47784131f0569462e65ca7babc39214bad9003954959e0c1844bb79e8534ddb9033be85d6e5d3fa521321b295745

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
